name = "gym-buddy-push"
main = "worker.js"
compatibility_date = "2025-09-01"
workers_dev = true

[[durable_objects.bindings]]
name = "TIMER"
class_name = "RestTimer"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["RestTimer"]
